### ISSUE TITLE
Only getting "Source" when using deb822.Packages.iter_paragraphs

### ISSUE THREAD

**Issue by BrunnerLivio** [romlok/python-debian#2]
Hey 

Python-Version: 2.7.12
OS: Ubuntu 16.04.01 Xenial Xerus

I ran the [degraph example](https://github.com/romlok/python-debian/blob/master/examples/deb822/depgraph) using the testfile.

Testfile: 
```
Source: python-debian
Section: python
Priority: optional
Maintainer: Debian python-debian Maintainers <pkg-python-debian-maint@lists.alioth.debian.org>
Uploaders: Adeodato Simó <dato@net.com.org.es>,
 Enrico Zini <enrico@debian.org>,
 James Westby <jw+debian@jameswestby.net>,
 Reinhard Tartler <siretart@tauware.de>,
 Stefano Zacchiroli <zack@debian.org>,
 John Wright <jsw@debian.org>
Build-Depends: debhelper (>= 5.0.37.2), python (>= 2.6.6-3~), python-setuptools, python-chardet
Standards-Version: 3.8.4
Vcs-Browser: http://git.debian.org/?p=pkg-python-debian/python-debian.git
Vcs-Git: git://git.debian.org/git/pkg-python-debian/python-debian.git
X-Python-Version: >= 2.5

Package: python-debian
Architecture: all
Depends: ${python:Depends}, ${misc:Depends}, python-chardet
Recommends: python-apt
Suggests: gpgv
Provides: python-deb822
Conflicts: python-deb822
Replaces: python-deb822
Description: Python modules to work with Debian-related data formats
 This package provides Python modules that abstract many formats of Debian
 related files. Currently handled are:
  * Debtags information (debian.debtags module)
  * debian/changelog (debian.changelog module)
  * Packages files, pdiffs (debian.debian_support module)
  * Control files of single or multiple RFC822-style paragraphs, e.g.
    debian/control, .changes, .dsc, Packages, Sources, Release, etc.
    (debian.deb822 module)
  * Raw .deb and .ar files, with (read-only) access to contained
    files and meta-information
```

 The example failed, and when I printed the returned object, I only recevied the 'Source'-part of the package. 
Returned object:
```
{  
   'Source':u'python-debian',
   'Section':u'python',
   'Priority':u'optional',
   'Maintainer':u'Debian python-debian Maintainers <pkg-python-debian-maint@lists.alioth.debian.org>',
   'Uploaders':u'Adeodato Sim\xf3 <dato@net.com.org.es>,
   \n Enrico Zini <enrico@debian.org>,
   \n James Westby <jw+debian@jameswestby.net>,
   \n Reinhard Tartler <siretart@tauware.de>,
   \n Stefano Zacchiroli <zack@debian.org>,
   \n John Wright <jsw@debian.org>',
   'Build-Depends':u'debhelper (>= 5.0.37.2),
   python (>= 2.6.6-3~),
   python-setuptools,
   python-chardet',
   'Standards-Version':u'3.8.4',
   'Vcs-Browser':   u'http://git.debian.org/?p=pkg-python-debian/python-debian.git',
   'Vcs-Git':   u'git://git.debian.org/git/pkg-python-debian/python-debian.git',
   'X-Python-Version':u'>= 2.5'
}
```

The example failed because of that:
Log:
```
digraph depgraph {
Traceback (most recent call last):
  File "/home/users/brunnel6/workspace/mk-deps/mk-deb.py", line 57, in <module>
    main()
  File "/home/users/brunnel6/workspace/mk-deps/mk-deb.py", line 40, in main
    name = pkg['package']
  File "/usr/lib/python2.7/dist-packages/debian/deb822.py", line 245, in __getitem__
```

Is this intended like this? Shouldn't I also get the packages?

PS: cool module, keep up the good work!

**Comment by romlok** [comment]
Sorry, but there's nothing official about this repo, and I don't think I can help you here. I really should have deactivated issues and whatnot, long ago!

If your issue is occurring using system packages, and not the code in this repo (which is 5 years out of date at this point), you might have better luck asking/reporting on Launchpad: https://launchpad.net/ubuntu/+source/python-debian
